# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ProjectFour' do

  use_frameworks!

  # Pods for ProjectFour

    	pod 'AsyncSwift'
	pod ‘SwiftSpinner’


  target 'ProjectFourTests' do
    inherit! :search_paths
    # Pods for testing

  end

end
